# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170822_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
