# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170823_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
