# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170823_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.PROTECT, to='profiles.Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='0.00'),
        ),
    ]
