# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170823_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
