# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170823_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 16, 57, 7, 597174), verbose_name='Date'),
        ),
    ]
