# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170823_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='time',
            name='remarks',
            field=models.CharField(default='remarks', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 26, 2, 45, 1, 639058), verbose_name='Date'),
        ),
    ]
