# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20170826_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 5, 44, 55, 188069), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 5, 44, 55, 188069), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='remarks',
            field=models.TextField(),
        ),
    ]
