# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20170827_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 15, 4, 39, 376669), verbose_name='Date'),
        ),
    ]
